//import the express module
const express = require("express");

//import the todos data
const todos = require("../data/todos");

//A built in methods in Express that creates a new isolated instance of middlewarew and routes.
const router = express.Router();

//GET /todos Return all todos
router.get("/", (req, res) => {
    res.status(200).json(todos);
});

//GET /todos/:id Return a single todo by id
router.get("/:id", (req, res) => {
    const id = Number(req.params.id);
    const todo = todos.find((todo) => todo.id === id);

    if (!todo) {
         return res.status(404).json({
            error: "Todo not found"
         });
    }
    res.status(200).json(todo);
});

//POST /todos Create a new todo
router.post("/", (req, res) => {
  const { title, notes, priority, done } = req.body;

// Title Validation to check whether the title is set and if it is a non-empty string
  if (typeof title !== "string" || title.trim() === "") {
    return res.status(400).json({
      error: "Title is required",
    });
  }

  const Priorities = ["low", "medium", "high"];

  // Priority validation to check whether the priority is set and if it is one of the allowed value
  if (priority !== undefined && !Priorities.includes(priority)) {
    return res.status(400).json({
      error: "Priority must be low, medium, or high",
    });
  }

  // Done validation to check whether the done is set and if it is a boolean
  if (done !== undefined && typeof done !== "boolean") {
    return res.status(400).json({
      error: "Done must be a boolean",
    });
  }

  // Create a new todo object with a unique id, title, notes, priority, and done status. The id is generated by finding the maximum id in the existing todos array and adding 1 to it. If there are no existing todos, the id is set to 1. The title is trimmed of whitespace, and the notes, priority, and done status are set to default values if they are not provided in the request body.
  const newTodo = {
    id: todos.length > 0 ? Math.max(...todos.map((todo) => todo.id)) + 1 : 1,
    title: title.trim(),
    notes: notes ?? "",
    priority: priority ?? "medium",
    done: done ?? false,
  };

  todos.push(newTodo);

  res.status(201).json(newTodo);
});

//PUT /todos/:id Update an existing todo by id
router.put("/:id", (req, res) => {
  const id = Number(req.params.id);

  const index = todos.findIndex((todo) => todo.id === id);

  // If the todo with the specified id is not found, return a 404 error response with a message indicating that the todo was not found.
  if (index === -1) {
    return res.status(404).json({
      error: "Todo not found",
    });
  }

  const { title, notes, priority, done } = req.body;


  // Validate the title, priority, and done fields in the request body. If any of these fields are invalid, return a 400 error response with an appropriate error message.
  if (typeof title !== "string" || title.trim() === "") {
    return res.status(400).json({
      error: "Title is required",
    });
  }

  const allowedPriorities = ["low", "medium", "high"];

  // Validate the priority field to ensure it is one of the allowed values. If it is not, return a 400 error response with an appropriate error message.
  if (!allowedPriorities.includes(priority)) {
    return res.status(400).json({
      error: "Priority must be low, medium, or high",
    });
  }

  // Validate the done field to ensure it is a boolean value. If it is not, return a 400 error response with an appropriate error message.
  if (typeof done !== "boolean") {
    return res.status(400).json({
      error: "Done must be a boolean",
    });
  }


  // Update the existing todo object with the new values from the request body. The title is trimmed of whitespace, and the notes, priority, and done status are updated with the new values provided in the request body.
  todos[index] = {
    id,
    title: title.trim(),
    notes: notes ?? "",
    priority,
    done,
  };

  res.status(200).json(todos[index]);
});

module.exports = router;